import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { repoUrl, files, commitMessage, issueTitle } = await request.json();
    
    if (!process.env.GITHUB_TOKEN) {
      return NextResponse.json(
        { error: 'GitHub token not configured' },
        { status: 500 }
      );
    }

    // Extract owner and repo from URL
    const urlParts = repoUrl.replace('https://github.com/', '').split('/');
    const owner = urlParts[0];
    const repo = urlParts[1];

    console.log('Repository details:', { repoUrl, owner, repo, urlParts });

    if (!owner || !repo) {
      return NextResponse.json(
        { error: 'Invalid repository URL format. Expected: https://github.com/owner/repo' },
        { status: 400 }
      );
    }

    // Create branch for the solution
    const branchName = `ai-solution-${Date.now()}`;
    
    // Get the default branch SHA
    const defaultBranchResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: {
        'Authorization': `token ${process.env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
      },
    });

    if (!defaultBranchResponse.ok) {
      const errorData = await defaultBranchResponse.json().catch(() => ({}));
      console.error('GitHub API Error:', {
        status: defaultBranchResponse.status,
        statusText: defaultBranchResponse.statusText,
        error: errorData
      });
      
      let errorMessage = 'Failed to access repository';
      if (defaultBranchResponse.status === 404) {
        errorMessage = 'Repository not found or no access permissions';
      } else if (defaultBranchResponse.status === 401) {
        errorMessage = 'Invalid GitHub token or insufficient permissions';
      } else if (defaultBranchResponse.status === 403) {
        errorMessage = 'GitHub token lacks required permissions (needs repo access)';
      }
      
      return NextResponse.json(
        { error: errorMessage },
        { status: defaultBranchResponse.status }
      );
    }

    const repoData = await defaultBranchResponse.json();
    const defaultBranch = repoData.default_branch;

    // Get the latest commit SHA from default branch
    const branchResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${defaultBranch}`, {
      headers: {
        'Authorization': `token ${process.env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
      },
    });

    const branchData = await branchResponse.json();
    const latestCommitSha = branchData.object.sha;

    // Create new branch
    await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers: {
        'Authorization': `token ${process.env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: latestCommitSha,
      }),
    });

    // Create/update files
    const filePromises = files.map(async (file: any) => {
      const content = Buffer.from(file.content).toString('base64');
      
      return fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${file.path}`, {
        method: 'PUT',
        headers: {
          'Authorization': `token ${process.env.GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: `AI Solution: ${file.description}`,
          content: content,
          branch: branchName,
        }),
      });
    });

    await Promise.all(filePromises);

    // Create pull request
    const prResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: {
        'Authorization': `token ${process.env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: `🤖 AI Solution: ${issueTitle}`,
        head: branchName,
        base: defaultBranch,
        body: `${commitMessage}\n\n---\n*This pull request was automatically generated by AI to resolve the issue.*\n\n**Files created/modified:**\n${files.map((f: any) => `- \`${f.path}\`: ${f.description}`).join('\n')}`,
      }),
    });

    const prData = await prResponse.json();

    return NextResponse.json({
      success: true,
      branch: branchName,
      pullRequest: {
        url: prData.html_url,
        number: prData.number,
      },
      message: 'AI solution committed and pull request created successfully!',
    });

  } catch (error) {
    console.error('GitHub commit error:', error);
    return NextResponse.json(
      { error: `Failed to commit to GitHub: ${error instanceof Error ? error.message : 'Unknown error'}` },
      { status: 500 }
    );
  }
}